const express = require("express");
const router = express.Router();
const bookController = require("../controllers/bookController");

// Get all books (Helper API)
router.get("/", bookController.getAllBooks);

// Get books by name or term
router.get("/search", bookController.searchBooks);

// Get books by rent price range
router.get("/rent-range", bookController.getBooksByRentRange);

// Get books by category, name/term, and rent range
router.get("/filter", bookController.filterBooks);

// Get book transactions
router.get("/:bookName/transactions", bookController.getBookTransactions);

// Get total rent generated by a book
router.get("/:bookName/total-rent", bookController.getTotalRentByBook);

module.exports = router;
